# Generated by Django 3.2.13 on 2022-11-07 07:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='liveresume',
            name='cvpayload',
        ),
    ]
